market = 'USDT'

assests_btc = {
    "BNB/BTC",
    "ETH/BTC",
    "ADA/BTC",
    "SOL/BTC",
    "XRP/BTC",
    "ATOM/BTC",
    "NEAR/BTC",
    "EGLD/BTC",

    "ALGO/BTC",
    "MATIC/BTC",
    "ONE/BTC",
    "ROSE/BTC",
    "TRX/BTC",
    "LINK/BTC",
    "SHIB/USDT",
    "FLOW/BTC",
    "DOT/BTC",
    "IOTA/BTC",
}

assests_curated = {
    "BTC/USDT",
    "BNB/USDT",
    "ETH/USDT",
    "ADA/USDT",
    "SOL/USDT",
    "XRP/USDT",
    "ATOM/USDT",
    "AVAX/USDT",

    "NEAR/USDT",
    "EGLD/USDT",
    "ALGO/USDT",
    "KSM/USDT",
    "MATIC/USDT",
    "ONE/USDT",

    "ROSE/USDT",
    "TRX/USDT",
    "ETC/USDT",
    "LINK/USDT",
    "UNI/USDT",

    "SHIB/USDT",
    "LDO/USDT",
    "EOS/USDT",
    "FLOW/USDT",
    "IOTA/USDT",
    "DASH/USDT",
    "KDA/USDT",
    "MANA/USDT"
}

assests_full = {
    "BTC/USDT",
    "BNB/USDT",
    "ETH/USDT",
    "ADA/USDT",
    "SOL/USDT",
    "XRP/USDT",
    "DOT/USDT",
    "ATOM/USDT",
    "HBAR/USDT",
    "IOTA/USDT",
    "AVAX/USDT",
    "ICP/USDT",

    "COTI/USDT",
    "NEAR/USDT",
    "BAT/USDT",
    "WAVES/USDT",
    "CHZ/USDT",
    "MINA/USDT",
    "EGLD/USDT",
    "XTZ/USDT",
    "ALGO/USDT",
    "KSM/USDT",
    "MATIC/USDT",
    "ONE/USDT",

    "1INCH/USDT",
    "KAVA/USDT",
    "OCEAN/USDT",
    "GRT/USDT",
    "ROSE/USDT",
    "CTSI/USDT",

    "ZRX/USDT",
    "TRX/USDT",
    "ETC/USDT",
    "BCH/USDT",
    "LINK/USDT",
    "FIL/USDT",
    "UNI/USDT",
    "GTC/USDT",
    "POND/USDT",

    "SHIB/USDT",
    "LDO/USDT",
    "EOS/USDT",
    "FLOW/USDT",
    "DYDX/USDT",
    "DASH/USDT",
    "KDA/USDT",
    "MANA/USDT",

    "DOGE/USDT",
    "FTT/USDT",
    "MKR/USDT",
    "CAKE/USDT",
    "AERGO/USDT",
}
